// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

// Fallbacks so the app still boots on hosts (Vercel, custom domains) where the
// VITE_* env vars were not configured. These are publishable/anon values.
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://iqosbhbbyzqozfgpthyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlxb3NiaGJieXpxb3pmZ3B0aHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg1NzgyNTMsImV4cCI6MjEwNDE1NDI1M30.7oNaInWRGvZXfnwc_zGTghRDuGuV84Rhj4Fi_zx48uA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});